tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_elite_fp\elite_ar_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_elite_fp\elite_ar_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_elite_fp\elite_ar_pose1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_elite_fp\elite_ar_pose2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_elite_fp\elite_ar_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_elite_fp\elite_ar_reload_empty weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_elite_fp\elite_ar_reload_full weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_fire weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_melee_1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_melee_2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_pose_1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_pose_2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_reload_empty weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_reload_full weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_tail_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\ar_tail_int weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\assault_rifle\assault_rifle_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_pose1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_pose2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_reloadempty weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_elite_fp\elite_dmr_reloadfull weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_melee_1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_melee_2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_pose_1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_pose_2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_reload_empty weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\dmr\dmr_reload_full weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_melee_1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_melee_2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_airlunge weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_airlunge_unaimed weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_drained_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_drained_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_lunge weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_lunge_unaimed weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword _fp\energy_sword_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword_drop object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword_lunge_cloth weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword_lunge_hum weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword_lunge_unaimed_airborne_cloth weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\energy_sword_pose weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_airlunge weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_airlunge_unaimed weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_drained_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_drained_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_lunge weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_lunge_unaimed weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_pose weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\plassword_elite_fp\elite_energy_sword_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\sword_impact_character projectile_impact
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\sword_impact_env projectile_impact
tool sounds-single-layer dw3\r3ach\sound\weapons\energy_sword\sword_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_ammo weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_drop object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_drop_soft object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_dryfire weapon_empty
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_eject weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_pose1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_pose2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_reloadempty weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_elite_fp\elite_magnum_reloadfull weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fire weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_melee_1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_melee_2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_pose_1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_pose_2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_reaload_empty weapon_empty
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_fp\magnum_reload_full weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_tails_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_tails_int weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_zoom_in game_event
tool sounds-single-layer dw3\r3ach\sound\weapons\magnum\magnum_zoom_out game_event
tool sounds-single-layer dw3\r3ach\sound\weapons\marksman_rifle\marksman_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\marksman_rifle\marksman_rifle_fire weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\marksman_rifle\marksman_tail_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\marksman_rifle\marksman_tail_int weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\dryfire weapon_empty
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\expl projectile_detonation
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_drop object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_drop_soft object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fire_reach weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_flyby projectile_flyby
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp\needler_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp\needler_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp\needler_pose1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp\needler_pose2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp\needler_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp\needler_ready_init weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp\needler_reload weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp_elite\needler_melee1_elite weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp_elite\needler_melee2_elite weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp_elite\needler_pose1_elite weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp_elite\needler_pose2_elite weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp_elite\needler_ready_elite weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp_elite\needler_ready_init_elite weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_fp_elite\needler_reload_elite weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_super_expl projectile_detonation
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needler_super_expl_lod_far projectile_detonation_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needle_ammo weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\needler\needle_ricc projectile_impact
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_bolt_by projectile_flyby
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_bolt_expl projectile_detonation
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fire weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp\needle_rifle_melee weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp\needle_rifle_posing1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp\needle_rifle_posing2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp\needle_rifle_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp\needle_rifle_ready_init weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp\needle_rifle_reload weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp_elite\nr_melee_elite weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp_elite\nr_posing1_elite weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp_elite\nr_posing2_elite weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp_elite\nr_ready_elite weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp_elite\nr_ready_init_elite weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_fp_elite\nr_reload_elite weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_zoom\needle_rifle_zoom_in game_event
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\needle_rifle_zoom\needle_rifle_zoom_out game_event
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\n_rifle_bolt_attached\attached_loop\loop projectile_flyby
tool sound-looping dw3\r3ach\sound\weapons\needle_rifle\n_rifle_bolt_attached projectile_flyby
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\n_rifle_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\n_rifle_ricc projectile_impact
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\n_rifle_tails_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\needle_rifle\n_rifle_tails_int weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasma_rifle_drop object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasma_rifle_drop_soft object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasma_rifle_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasma_rifle_tails_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasma_rifle_tails_int weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_oh weapon_overheat
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_oh_exit weapon_overheat
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_pose1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_pose2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_elite_fp\elite_plasmarifle_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_oh_exit weapon_overheat
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_overheat weapon_overheat
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_posing_one weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_posing_zero weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plasrifle_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plas_rif_fire_reach weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\plas_rif_init_fire_reach\plas_rif_init_fire\in weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\plasma_rifle\prifle_heat_loop\prifle_heat_loop\loop weapon_overheat
tool sound-looping dw3\r3ach\sound\weapons\plasma_rifle\prifle_heat_loop weapon_overheat
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\fire weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_ammo weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_drop object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_drop_soft object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_fire1 weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_fire2 weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_fire3 weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_pose1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_pose2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_reload_enter weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_reload_exit weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_elite_fp\elite_sg_reload_loop weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_fire1 weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_fire2 weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_fire3 weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_melee1 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_melee2 weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_posing0 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_posing1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_ready_hero weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_reload_enter weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_reload_exit weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_fp\sg_reload_loop weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_tails_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\shotgun\shotgun_tails_int weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\fire_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_ammo weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_drop object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_eject weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_fire_reach weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_drop_soft object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp\sr_melee weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp\sr_posing weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp\sr_posing_var2 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp\sr_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp\sr_ready_init weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp\sr_reload weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp\sr_reload_empty weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp_elite\sr_melee1_elite weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp_elite\sr_posing1_elite weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp_elite\sr_posing2_elite weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp_elite\sr_ready_elite weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp_elite\sr_ready_init_elite weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp_elite\sr_reload_elite weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_rifle_fp_elite\sr_reload_empty_elite weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_tail_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\sniper_tail_inside weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\zoom_in game_event
tool sounds-single-layer dw3\r3ach\sound\weapons\sniper_rifle\zoom_out game_event
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\fp_spike_rifle\fp_spike_rifle_melee weapon_melee
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\fp_spike_rifle\fp_spike_rifle_posing_var1 weapon_idle
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\fp_spike_rifle\fp_spike_rifle_ready weapon_ready
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\fp_spike_rifle\fp_spike_rifle_reload_full weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_flyby projectile_flyby
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_impacts projectile_impact
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_impacts_dirt projectile_impact
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_impacts_soft projectile_impact
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_lod_far weapon_fire_lod
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_rifle_ammo weapon_reload
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_rifle_drops\spike_rifle_drop object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_rifle_drops\spike_rifle_drop_dirt object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_rifle_drops\spike_rifle_drop_soft object_impacts
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_rifle_fire weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_rifle_tails_ext weapon_fire
tool sounds-single-layer dw3\r3ach\sound\weapons\spike_rifle\spike_rifle_tails_int weapon_fire
